#!/usr/bin/env tsx
/**
 * Sync Environment Variables to Wrangler .dev.vars
 * 
 * This script reads your .env file and generates .dev.vars for Wrangler local development.
 * It extracts server-side variables (those WITHOUT VITE_ prefix) and writes them to .dev.vars
 * 
 * Usage:
 *   pnpm tsx scripts/sync-wrangler-vars.ts
 * 
 * What it does:
 *   - Reads .env file
 *   - Filters server-only variables (no VITE_ prefix)
 *   - Writes to .dev.vars for Wrangler
 *   - Skips client-side VITE_ variables (not needed in Workers)
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

// ANSI colors
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  bold: '\x1b[1m',
}

function log(color: keyof typeof colors, message: string) {
  console.log(`${colors[color]}${message}${colors.reset}`)
}

function logError(message: string) {
  log('red', `❌ ${message}`)
}

function logSuccess(message: string) {
  log('green', `✅ ${message}`)
}

function logInfo(message: string) {
  log('blue', `ℹ️  ${message}`)
}

// Parse .env file manually (simple parser)
function parseEnvFile(content: string): Record<string, string> {
  const vars: Record<string, string> = {}
  const lines = content.split('\n')

  for (const line of lines) {
    const trimmed = line.trim()
    
    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) {
      continue
    }

    // Match KEY=VALUE or KEY="VALUE"
    const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/)
    if (match) {
      const [, key, value] = match
      // Remove quotes if present
      const cleanValue = value.replace(/^["']|["']$/g, '')
      vars[key] = cleanValue
    }
  }

  return vars
}

// Main script
const envPath = join(process.cwd(), '.env')
const devVarsPath = join(process.cwd(), '.dev.vars')

// Check if .env exists
if (!existsSync(envPath)) {
  logError('.env file not found!')
  logInfo('Create a .env file first by copying .env.example:')
  console.log('  cp .env.example .env')
  process.exit(1)
}

logInfo('Reading .env file...')
const envContent = readFileSync(envPath, 'utf-8')
const envVars = parseEnvFile(envContent)

// Filter server-only variables (exclude VITE_ prefix)
const serverVars = Object.entries(envVars).filter(
  ([key]) => !key.startsWith('VITE_')
)

if (serverVars.length === 0) {
  logError('No server-side variables found in .env')
  logInfo('Make sure you have variables without VITE_ prefix')
  process.exit(1)
}

logInfo(`Found ${serverVars.length} server-side variable(s)`)

// Build .dev.vars content
const devVarsContent = `# .dev.vars - Wrangler Local Development Variables
# 
# ⚠️ AUTO-GENERATED by scripts/sync-wrangler-vars.ts
# ⚠️ DO NOT EDIT MANUALLY - Edit .env instead and run: pnpm sync-wrangler
# 
# This file contains server-side secrets for local Wrangler development.
# These variables are available in your Worker via env parameter.
# 
# Generated: ${new Date().toISOString()}

${serverVars.map(([key, value]) => `${key}="${value}"`).join('\n')}
`

// Write to .dev.vars
logInfo('Writing to .dev.vars...')
writeFileSync(devVarsPath, devVarsContent, 'utf-8')

logSuccess('.dev.vars created successfully!')
console.log('')
logInfo('Variables synced:')
for (const [key] of serverVars) {
  console.log(`  • ${key}`)
}

console.log('')
logInfo('For production deployment, set these variables in Cloudflare Dashboard or via:')
console.log('  wrangler secret put <KEY>')
console.log('')
logSuccess('Done! You can now run: pnpm wrangler dev')
